### ISSUE TITLE
Error when executing e2e tests

### ISSUE THREAD

**Issue by AlvasanG** [Arquisoft/dechat_en2a#79]
As I execute ng e2e command I am prompted with an error that states the following:

> events.js:174
      throw er; // Unhandled 'error' event
      ^
Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:750:20)
    at ChildProcess.target.send (internal/child_process.js:634:19)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (C:\Users\Alvaro\Desktop\2ndSemester\ASW\dechat_en2a\node_modules\@angular-devkit\build-angular\src\utils\run-module-as-observable-fork.js:57:23)
    at Observable.subscribe (C:\Users\Alvaro\Desktop\2ndSemester\ASW\dechat_en2a\node_modules\rxjs\internal\Observable.js:162:69)
    at C:\Users\Alvaro\Desktop\2ndSemester\ASW\dechat_en2a\node_modules\rxjs\internal\util\subscribeTo.js:22:31
    at Object.subscribeToResult (C:\Users\Alvaro\Desktop\2ndSemester\ASW\dechat_en2a\node_modules\rxjs\internal\util\subscribeToResult.js:7:45)
    at MergeMapSubscriber._innerSub (C:\Users\Alvaro\Desktop\2ndSemester\ASW\dechat_en2a\node_modules\rxjs\internal\operators\mergeMap.js:132:38)
    at MergeMapSubscriber._tryNext (C:\Users\Alvaro\Desktop\2ndSemester\ASW\dechat_en2a\node_modules\rxjs\internal\operators\mergeMap.js:129:14)
    at MergeMapSubscriber._next (C:\Users\Alvaro\Desktop\2ndSemester\ASW\dechat_en2a\node_modules\rxjs\internal\operators\mergeMap.js:112:18)
    at MergeMapSubscriber.Subscriber.next (C:\Users\Alvaro\Desktop\2ndSemester\ASW\dechat_en2a\node_modules\rxjs\internal\Subscriber.js:103:18)
    at MergeMapSubscriber.notifyNext (C:\Users\Alvaro\Desktop\2ndSemester\ASW\dechat_en2a\node_modules\rxjs\internal\operators\mergeMap.js:141:26)
    at InnerSubscriber._next (C:\Users\Alvaro\Desktop\2ndSemester\ASW\dechat_en2a\node_modules\rxjs\internal\InnerSubscriber.js:30:21)
    at InnerSubscriber.Subscriber.next (C:\Users\Alvaro\Desktop\2ndSemester\ASW\dechat_en2a\node_modules\rxjs\internal\Subscriber.js:103:18)
    at C:\Users\Alvaro\Desktop\2ndSemester\ASW\dechat_en2a\node_modules\rxjs\internal\util\subscribeToPromise.js:7:24
    at process._tickCallback (internal/process/next_tick.js:68:7)
Emitted 'error' event at:
    at process.nextTick (internal/child_process.js:754:39)
    at process._tickCallback (internal/process/next_tick.js:61:11)

It is an error based on rxjs so I thought about executing `npm update`, but since our Angular version is lower than the latest from rxjs it would throw another error plus the aforementioned error.

Might be also based on observable as discussed in #74 

If anyone has faced this issue or has any clue how to fix it I would appreciate it

**Comment by pastrana98** [comment]
#72 It is already solved
